---

- name: install icingaweb2
  package:
    name:
      - icingaweb2
      - icingaweb2-module-ipl
    state: present

- name: install python packages for support databases
  pip:
    name: "{{ item }}"
    executable: pip3
    state: present
  loop:
    - "{{ icingaweb_python_packages }}"


...
