---

- include: prepare.yml
  become: true
  tags:
    - icingaweb_prepare
    - icingaweb_configure

- include: install.yml
  become: true
  tags:
    - icingaweb_install

- include: configure.yml
  become: true
  tags:
    - icingaweb_configure

- name: install themes
  include_tasks: themes/install.yml
  tags:
    - icingaweb_themes

- name: external modules
  include_tasks: modules/install.yml
  tags:
    - icingaweb_modules
