---

# - debug:
#     var: "{{ item }}"
#   when: item is defined
#   loop:
#     - ansible_python_interpreter

#- name: external modules
#  include_tasks: modules/install.yml

- include: preparations.yml
  become: true
  tags:
    - preparations

- include: installation.yml
  become: true
  tags:
    - installation

- include: configure.yml
  become: true
  tags:
    - configure
