---

- name: create local temp directory
  become: false
  delegate_to: 127.0.0.1
  file:
    path: "{{ icingaweb_local_tmp_directory }}"
    state: directory
    mode: 0755

- name: detect installed php version  # noqa 301 306
  shell: "php -v 2> /dev/null | grep NTS | awk -F 'PHP ' '{printf $2}' | cut -d . -f 1-2"
  register: __installed_php_version

- name: define php version.
  set_fact:
    php_version: "{{ __installed_php_version.stdout }}"
  when:
    - __installed_php_version is defined
    - __installed_php_version.rc is defined
    - __installed_php_version.rc == 0

- name: assert PHP Version
  assert:
    that: php_version is version_compare('7.0', '>=')
    msg: "This role only works with PHP >= 7.0 .. found: {{ php_version }}"

- name: merge dependencies between defaults and custom
  set_fact:
    icingaweb_dependencies: "{{ icingaweb_dependencies + icingaweb_packages }}"

- name: merge dependencies between defaults and custom for enabled icingaweb modules
  set_fact:
    icingaweb_modules_enabled: "{{ icingaweb_modules_enabled_defaults + icingaweb_modules_enabled }}"

- name: merge icingaweb_authentication configuration between defaults and custom
  set_fact:
    icingaweb_authentication: "{{ icingaweb_authentication_defaults |
      combine( icingaweb_authentication, recursive=True ) }}"

- name: merge icingaweb_resources configuration between defaults and custom
  set_fact:
    icingaweb_resources: "{{ icingaweb_resources_defaults |
      combine( icingaweb_resources, recursive=True ) }}"

- name: install requirements
  package:
    name: "{{ icingaweb_dependencies }}"
    state: present
