---

- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''

  pre_tasks:
    - name: detect python3
      stat:
        path: /usr/bin/python3
      register: __stat_present_python3
      changed_when: not __stat_present_python3.stat.exists

    - name: set python3
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when:
        - ansible_python.version.major == 2
        - __stat_present_python3.stat.exists

    - name: Gathering Facts now
      setup:

    - debug:
        msg:
          - "ansible_os_family                  : {{ ansible_os_family }}"
          - "ansible_distribution               : {{ ansible_distribution }}"
          - "ansible_distribution_major_version : {{ ansible_distribution_major_version }}"
          - "ansible_version                    : {{ ansible_version.full }}"
          - "ansible_python_version             : {{ ansible_python.version.major }}"

  roles:
    - role: bodsch.icingaweb2
